# config/settings.yml

# 送信したいチャンネルの情報のリスト
targets:
  - name: "diary_reminder_job"
    webhook_url_env: "DIARY_REMINDER_WEBHOOK_URL"
    schedule_time: "21:00" # JST
    message: "日記を書こうね"
    weekday_only: false
